version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: JavaSeriesLibrary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: JavaSeriesLibrary
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: